import type { Customer, Supplier, Order } from "../types";

export const mockCustomers: Customer[] = [
    {
        _id: "cust_001",
        name: "Arjun Mehta",
        mobile: "+91-9876543210",
        country: "India",
        state: "Maharashtra",
        pincode: "400001",
        bank_details: "HDFC Bank | A/C: 0012345678 | IFSC: HDFC0001234",
        company_address: "12, Nariman Point, Mumbai, Maharashtra",
        company_name: "Mehta Steels Pvt. Ltd.",
    },
    {
        _id: "cust_002",
        name: "Priya Nair",
        mobile: "+91-9123456789",
        country: "India",
        state: "Kerala",
        pincode: "682001",
        bank_details: "SBI | A/C: 9988776655 | IFSC: SBIN0001001",
        company_address: "45, MG Road, Ernakulam, Kerala",
        company_name: "Nair Commodities Ltd.",
    },
    {
        _id: "cust_003",
        name: "Ranjit Oberoi",
        mobile: "+91-9871234560",
        country: "India",
        state: "Punjab",
        pincode: "141001",
        bank_details: "PNB | A/C: 1122334455 | IFSC: PUNB0001200",
        company_address: "7, Ferozepur Road, Ludhiana, Punjab",
        company_name: "Oberoi Metals & Alloys",
    },
    {
        _id: "cust_004",
        name: "Sunita Kapoor",
        mobile: "+91-9988001122",
        country: "India",
        state: "Gujarat",
        pincode: "380001",
        bank_details: "Axis Bank | A/C: 4455667788 | IFSC: UTIB0000002",
        company_address: "22, Ashram Road, Ahmedabad, Gujarat",
        company_name: "Kapoor Industries",
    },
    {
        _id: "cust_005",
        name: "Vikram Choudhary",
        mobile: "+91-9001234567",
        country: "India",
        state: "Rajasthan",
        pincode: "302001",
        bank_details: "ICICI Bank | A/C: 6677889900 | IFSC: ICIC0001111",
        company_address: "88, Tonk Road, Jaipur, Rajasthan",
        company_name: "Choudhary Exports",
    },
];

export const mockSuppliers: Supplier[] = [
    {
        _id: "supp_001",
        name: "Wang Lei",
        mobile: "+86-13812345678",
        country: "China",
        state: "Guangdong",
        pincode: "510000",
        bank_details: "Bank of China | A/C: CN8801234567 | SWIFT: BKCHCNBJ",
        company_address: "Tower 3, Guangzhou Trade Centre, Guangdong",
        company_name: "Guangzhou Metal Works Co.",
    },
    {
        _id: "supp_002",
        name: "Muhammad Al-Rashid",
        mobile: "+971-501234567",
        country: "UAE",
        state: "Dubai",
        pincode: "12345",
        bank_details: "Emirates NBD | A/C: AE070331234567890123456 | SWIFT: EBILAEAD",
        company_address: "Jebel Ali Free Zone, Dubai, UAE",
        company_name: "Al-Rashid Trading LLC",
    },
    {
        _id: "supp_003",
        name: "Park Joon-ho",
        mobile: "+82-10-1234-5678",
        country: "South Korea",
        state: "Incheon",
        pincode: "21999",
        bank_details: "Kookmin Bank | A/C: KR1004001234567890 | SWIFT: CZNBKRSE",
        company_address: "45 Free Economic Zone, Incheon, South Korea",
        company_name: "Korea Steel International",
    },
    {
        _id: "supp_004",
        name: "Tanaka Hiroshi",
        mobile: "+81-3-1234-5678",
        country: "Japan",
        state: "Tokyo",
        pincode: "100-0001",
        bank_details: "Mizuho Bank | A/C: JP1001234567890 | SWIFT: MHCBJPJT",
        company_address: "2-1 Marunouchi, Chiyoda, Tokyo, Japan",
        company_name: "Tanaka Materials Corp.",
    },
];

export const mockOrders: Order[] = [
    {
        _id: "ord_001",
        bill_of_lading_number: "MBOL2024001",
        cha: "Clearance Agent Alpha",
        customer_id: "cust_001",
        supplier_id: "supp_001",
        dilevery: "CIF Mumbai",
        expected_to_arrive: "2024-03-15",
        loading_date: "2024-02-10",
        shipped_on_date: "2024-02-12",
        mill_payment_status: "Paid",
        mill_payment: 850000,
        port_of_destination: "INNSA1 - Nhava Sheva",
        port_of_loading: "CNNGB - Ningbo",
        purchase_price: "₹42,50,000",
        selling_price: "₹48,00,000",
        shipping_line: "COSCO Shipping",
        country_of_origin_of_goods: "China",
        freight_cost: 120000,
        shipping_line_cost: 85000,
        createdAt: "2024-02-05",
        materials: [
            {
                _id: "mat_001a",
                container_number: "CSNU6789012",
                gross_weight: 22500,
                net_weight: 22000,
                material_description: "Hot Rolled Steel Coils - Grade SS400",
                sales_bill_price: 2100000,
                selling_price_with_gst: 2478000,
                gst_amount_sales_bill: 378000,
                total_duty: 155000,
                purchase_price_per_unit: 85.5,
                bill_of_entry: "BOE/2024/001A",
                images: [{ url: "https://picsum.photos/seed/steel1/400/300" }],
            },
            {
                _id: "mat_001b",
                container_number: "MSCU8901234",
                gross_weight: 21800,
                net_weight: 21300,
                material_description: "Cold Rolled Steel Sheets - Grade SPCC",
                sales_bill_price: 2150000,
                selling_price_with_gst: 2537000,
                gst_amount_sales_bill: 387000,
                total_duty: 162000,
                purchase_price_per_unit: 91.2,
                bill_of_entry: "BOE/2024/001B",
                images: [],
            },
        ],
        docs: [
            {
                _id: "doc_001a",
                clearing_price: "₹15,000",
                created_at: "2024-02-10",
                doc_name: "Bill of Lading",
                doc_type: "Shipping",
                doc_url: "https://example.com/docs/bol_001.pdf",
                gross_weight: 44300,
                net_weight: 43300,
                issued_by: "COSCO Shipping Lines",
                total_value: "₹42,50,000",
            },
            {
                _id: "doc_001b",
                clearing_price: "₹8,000",
                created_at: "2024-02-10",
                doc_name: "Commercial Invoice",
                doc_type: "Financial",
                doc_url: "https://example.com/docs/inv_001.pdf",
                gross_weight: 44300,
                net_weight: 43300,
                issued_by: "Guangzhou Metal Works Co.",
                total_value: "₹42,50,000",
            },
        ],
    },
    {
        _id: "ord_002",
        bill_of_lading_number: "EBOL2024007",
        cha: "Global Clearance Services",
        customer_id: "cust_002",
        supplier_id: "supp_002",
        dilevery: "FOB Dubai",
        expected_to_arrive: "2024-04-20",
        loading_date: "2024-03-18",
        shipped_on_date: "2024-03-20",
        mill_payment_status: "Pending",
        mill_payment: 0,
        port_of_destination: "INCCU1 - Kolkata",
        port_of_loading: "AEJEA - Jebel Ali",
        purchase_price: "₹31,00,000",
        selling_price: "₹35,50,000",
        shipping_line: "MSC Mediterranean",
        country_of_origin_of_goods: "UAE",
        freight_cost: 98000,
        shipping_line_cost: 72000,
        createdAt: "2024-03-10",
        materials: [
            {
                _id: "mat_002a",
                container_number: "MSCU3456789",
                gross_weight: 18900,
                net_weight: 18400,
                material_description: "Aluminium Ingots - Grade 6061",
                sales_bill_price: 1550000,
                selling_price_with_gst: 1829000,
                gst_amount_sales_bill: 279000,
                total_duty: 118000,
                purchase_price_per_unit: 76.8,
                bill_of_entry: "BOE/2024/007A",
                images: [{ url: "https://picsum.photos/seed/alum/400/300" }],
            },
        ],
        docs: [
            {
                _id: "doc_002a",
                clearing_price: "₹12,500",
                created_at: "2024-03-18",
                doc_name: "Packing List",
                doc_type: "Shipping",
                doc_url: "https://example.com/docs/pl_002.pdf",
                gross_weight: 18900,
                net_weight: 18400,
                issued_by: "Al-Rashid Trading LLC",
                total_value: "₹31,00,000",
            },
        ],
    },
    {
        _id: "ord_003",
        bill_of_lading_number: "KBOL2024012",
        cha: "Premium CHA Services",
        customer_id: "cust_003",
        supplier_id: "supp_003",
        dilevery: "CIF Chennai",
        expected_to_arrive: "2024-05-08",
        loading_date: "2024-04-02",
        shipped_on_date: "2024-04-05",
        mill_payment_status: "Partial",
        mill_payment: 500000,
        port_of_destination: "INMAA1 - Chennai",
        port_of_loading: "KRINC - Incheon",
        purchase_price: "₹56,00,000",
        selling_price: "₹63,00,000",
        shipping_line: "HMM Hyundai",
        country_of_origin_of_goods: "South Korea",
        freight_cost: 145000,
        shipping_line_cost: 110000,
        createdAt: "2024-03-28",
        materials: [
            {
                _id: "mat_003a",
                container_number: "HMCU1234567",
                gross_weight: 26200,
                net_weight: 25700,
                material_description: "Stainless Steel Pipes - Grade 304",
                sales_bill_price: 2800000,
                selling_price_with_gst: 3304000,
                gst_amount_sales_bill: 504000,
                total_duty: 210000,
                purchase_price_per_unit: 105.5,
                bill_of_entry: "BOE/2024/012A",
                images: [],
            },
            {
                _id: "mat_003b",
                container_number: "HMCU7654321",
                gross_weight: 25800,
                net_weight: 25300,
                material_description: "Stainless Steel Flanges - Grade 316",
                sales_bill_price: 2800000,
                selling_price_with_gst: 3304000,
                gst_amount_sales_bill: 504000,
                total_duty: 210000,
                purchase_price_per_unit: 110.0,
                bill_of_entry: "BOE/2024/012B",
                images: [{ url: "https://picsum.photos/seed/pipe/400/300" }],
            },
        ],
        docs: [],
    },
    {
        _id: "ord_004",
        bill_of_lading_number: "JBOL2024019",
        cha: "Sunrise Customs Agency",
        customer_id: "cust_004",
        supplier_id: "supp_004",
        dilevery: "EXW Tokyo",
        expected_to_arrive: "2024-06-01",
        loading_date: "2024-05-01",
        shipped_on_date: "",
        mill_payment_status: "Paid",
        mill_payment: 1200000,
        port_of_destination: "INMUN1 - Mundra",
        port_of_loading: "JPTYO - Tokyo",
        purchase_price: "₹78,00,000",
        selling_price: "₹88,50,000",
        shipping_line: "NYK Line",
        country_of_origin_of_goods: "Japan",
        freight_cost: 185000,
        shipping_line_cost: 140000,
        createdAt: "2024-04-20",
        materials: [],
        docs: [],
    },
    {
        _id: "ord_005",
        bill_of_lading_number: "CBOL2024025",
        cha: "Clearance Agent Alpha",
        customer_id: "cust_005",
        supplier_id: "supp_001",
        dilevery: "CFR Mundra",
        expected_to_arrive: "2024-04-10",
        loading_date: "2024-03-05",
        shipped_on_date: "2024-03-07",
        mill_payment_status: "Paid",
        mill_payment: 920000,
        port_of_destination: "INMUN1 - Mundra",
        port_of_loading: "CNSHA - Shanghai",
        purchase_price: "₹46,00,000",
        selling_price: "₹52,00,000",
        shipping_line: "Evergreen Marine",
        country_of_origin_of_goods: "China",
        freight_cost: 125000,
        shipping_line_cost: 90000,
        createdAt: "2024-02-28",
        materials: [
            {
                _id: "mat_005a",
                container_number: "EGLV1234567",
                gross_weight: 24100,
                net_weight: 23600,
                material_description: "Copper Cathodes - Grade A",
                sales_bill_price: 2300000,
                selling_price_with_gst: 2714000,
                gst_amount_sales_bill: 414000,
                total_duty: 175000,
                purchase_price_per_unit: 98.3,
                bill_of_entry: "BOE/2024/025A",
                images: [],
            },
        ],
        docs: [
            {
                _id: "doc_005a",
                clearing_price: "₹18,000",
                created_at: "2024-03-05",
                doc_name: "Certificate of Origin",
                doc_type: "Customs",
                doc_url: "https://example.com/docs/coo_005.pdf",
                gross_weight: 24100,
                net_weight: 23600,
                issued_by: "China Chamber of Commerce",
                total_value: "₹46,00,000",
            },
            {
                _id: "doc_005b",
                clearing_price: "₹9,000",
                created_at: "2024-03-05",
                doc_name: "Bill of Lading",
                doc_type: "Shipping",
                doc_url: "https://example.com/docs/bol_005.pdf",
                gross_weight: 24100,
                net_weight: 23600,
                issued_by: "Evergreen Marine Corp.",
                total_value: "₹46,00,000",
            },
        ],
    },
];